export const dummyProducts = [
    // Organic Veggies
    {
        name: "Potato 500g",
        category: "Organic Veggies",
        price: 25,
        offerPrice: 20,
        image: ["../assets/potato_image_1.png", "../assets/potato_image_2.png", "../assets/potato_image_3.png", "../assets/potato_image_4.png"],
        description: ["Fresh and organic", "Rich in carbohydrates", "Ideal for curries and fries"],
        inStock: true,
    },
    {
        name: "Tomato 1kg",
        category: "Organic Veggies",
        price: 40,
        offerPrice: 35,
        image: ["../assets/tomato_image.png"],
        description: ["Juicy and ripe", "Rich in Vitamin C", "Perfect for salads and sauces"],
        inStock: true,
    },
    {
        name: "Carrot 500g",
        category: "Organic Veggies",
        price: 30,
        offerPrice: 28,
        image: ["../assets/carrot_image.png"],
        description: ["Sweet and crunchy", "Good for eyesight", "Ideal for juices"],
        inStock: true,
    },
    {
        name: "Spinach 500g",
        category: "Organic Veggies",
        price: 18,
        offerPrice: 15,
        image: ["../assets/spinach_image_1.png"],
        description: ["Rich in iron", "High in vitamins", "Perfect for soups"],
        inStock: true,
    },
    {
        name: "Onion 500g",
        category: "Organic Veggies",
        price: 22,
        offerPrice: 19,
        image: ["../assets/onion_image_1.png"],
        description: ["Fresh and pungent", "Kitchen staple", "Perfect for cooking"],
        inStock: true,
    },

    // Fruits
    {
        name: "Apple 1kg",
        category: "Fresh Fruits",
        price: 120,
        offerPrice: 110,
        image: ["../assets/apple_image.png"],
        description: ["Crisp and juicy", "Rich in fiber", "Boosts immunity"],
        inStock: true,
    },
    {
        name: "Orange 1kg",
        category: "Fresh Fruits",
        price: 80,
        offerPrice: 75,
        image: ["../assets/orange_image.png"],
        description: ["Juicy and sweet", "Rich in Vitamin C", "Perfect for juice"],
        inStock: true,
    },
    {
        name: "Banana 1kg",
        category: "Fresh Fruits",
        price: 50,
        offerPrice: 45,
        image: ["../assets/banana_image_1.png"],
        description: ["Sweet and ripe", "High in potassium", "Great for smoothies"],
        inStock: true,
    },
    {
        name: "Mango 1kg",
        category: "Fresh Fruits",
        price: 150,
        offerPrice: 140,
        image: ["../assets/mango_image_1.png"],
        description: ["Sweet and flavorful", "Rich in Vitamin A", "Perfect for desserts"],
        inStock: true,
    },
    {
        name: "Grapes 500g",
        category: "Fresh Fruits",
        price: 70,
        offerPrice: 65,
        image: ["../assets/grapes_image_1.png"],
        description: ["Fresh and juicy", "Rich in antioxidants", "Healthy snack"],
        inStock: true,
    },

    // Dairy
    {
        name: "Milk 1L",
        category: "Dairy Products",
        price: 60,
        offerPrice: 55,
        image: ["../assets/amul_milk_image.png"],
        description: ["Pure and fresh", "Rich in calcium", "Daily essential"],
        inStock: true,
    },
    {
        name: "Paneer 200g",
        category: "Dairy Products",
        price: 90,
        offerPrice: 85,
        image: ["../assets/paneer_image.png"],
        description: ["Soft and fresh", "Rich in protein", "Perfect for curries"],
        inStock: true,
    },
    {
        name: "Eggs 12 pcs",
        category: "Dairy Products",
        price: 90,
        offerPrice: 85,
        image: ["../assets/eggs_image.png"],
        description: ["Farm fresh", "High protein", "Breakfast essential"],
        inStock: true,
    },
    {
        name: "Cheese 200g",
        category: "Dairy Products",
        price: 140,
        offerPrice: 130,
        image: ["../assets/cheese_image.png"],
        description: ["Creamy and tasty", "Perfect for pizza", "Rich in calcium"],
        inStock: true,
    },

    // Cold Drinks
    {
        name: "Coca Cola 1.5L",
        category: "Cold Drinks",
        price: 80,
        offerPrice: 75,
        image: ["../assets/coca_cola_image.png"],
        description: ["Refreshing", "Perfect for parties", "Serve chilled"],
        inStock: true,
    },
    {
        name: "Pepsi 1.5L",
        category: "Cold Drinks",
        price: 78,
        offerPrice: 73,
        image: ["../assets/pepsi_image.png"],
        description: ["Chilled drink", "Refreshing taste", "Party essential"],
        inStock: true,
    },
    {
        name: "Sprite 1.5L",
        category: "Cold Drinks",
        price: 79,
        offerPrice: 74,
        image: ["../assets/sprite_image_1.png"],
        description: ["Lemon flavor", "Refreshing", "Best in summer"],
        inStock: true,
    },
    {
        name: "Fanta 1.5L",
        category: "Cold Drinks",
        price: 77,
        offerPrice: 72,
        image: ["../assets/fanta_image_1.png"],
        description: ["Sweet and fizzy", "Orange flavor", "Loved by all"],
        inStock: true,
    },

    // Grains
    {
        name: "Basmati Rice 5kg",
        category: "Grains & Cereals",
        price: 550,
        offerPrice: 520,
        image: ["../assets/basmati_rice_image.png"],
        description: ["Long grain", "Aromatic", "Perfect for biryani"],
        inStock: true,
    },
    {
        name: "Wheat Flour 5kg",
        category: "Grains & Cereals",
        price: 250,
        offerPrice: 230,
        image: ["../assets/wheat_flour_image.png"],
        description: ["Soft rotis", "Healthy", "Daily use"],
        inStock: true,
    },
    {
        name: "Brown Rice 1kg",
        category: "Grains & Cereals",
        price: 120,
        offerPrice: 110,
        image: ["../assets/brown_rice_image.png"],
        description: ["Healthy option", "Rich in fiber", "Weight friendly"],
        inStock: true,
    },

    // Bakery
    {
        name: "Brown Bread",
        category: "Bakery & Breads",
        price: 40,
        offerPrice: 35,
        image: ["../assets/brown_bread_image.png"],
        description: ["Soft", "Healthy", "Breakfast ready"],
        inStock: true,
    },
    {
        name: "Croissant",
        category: "Bakery & Breads",
        price: 50,
        offerPrice: 45,
        image: ["../assets/butter_croissant_image.png"],
        description: ["Buttery", "Flaky", "Snack item"],
        inStock: true,
    },
    {
        name: "Chocolate Cake",
        category: "Bakery & Breads",
        price: 350,
        offerPrice: 325,
        image: ["../assets/chocolate_cake_image.png"],
        description: ["Rich taste", "Soft", "Perfect for parties"],
        inStock: true,
    },

    // Instant
    {
        name: "Maggi",
        category: "Instant Food",
        price: 55,
        offerPrice: 50,
        image: ["../assets/maggi_image.png"],
        description: ["2 min food", "Tasty", "Popular"],
        inStock: true,
    },
    {
        name: "Top Ramen",
        category: "Instant Food",
        price: 45,
        offerPrice: 40,
        image: ["../assets/top_ramen_image.png"],
        description: ["Quick", "Spicy", "Easy to cook"],
        inStock: true,
    },
    {
        name: "Knorr Soup",
        category: "Instant Food",
        price: 35,
        offerPrice: 30,
        image: ["../assets/knorr_soup_image.png"],
        description: ["Healthy", "Quick", "Light meal"],
        inStock: true,
    },
    {
        name: "Yippee Noodles",
        category: "Instant Food",
        price: 50,
        offerPrice: 45,
        image: ["../assets/yippee_image.png"],
        description: ["Non-fried", "Tasty", "Better option"],
        inStock: true,
    }
];